#!/usr/bin/env python

def build(bld):
	prog = bld(features='cc cshlib')
	# symbolic name used to reference this object
	prog.name = 'scratch-lib.shlib'
	# name of the resulting program
	prog.target = 'scratch-lib'
	prog.source = 'gtksourceview-3.0.vala'
	prog.includes = '..'
	# libraries to link against
	prog.uselib = 'GOBJECT'
	# Vala packages to use
	#prog.packages = ''
	# Extra vapi dirs
	#prog.vapi_dirs = '../my_lib ../my_other_lib'
	# Enable threading
	#prog.threading = True
